chore: use yarn workspaces
applicaster/ZappAppleBuilder pull request #422
Opened 2022-07-04 07:43 UTC by f-roland

🚧  IN PROGRESS 🚧 

## Description

This PR updates the repo to use yarn workspaces

## Affected platform

- [ ] iOS
- [ ] tvOS

### Checklist

- [ ] I've provided a readable title for the PR
- [ ] the title of the PR follows the [conventional commits specifications](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#specification)
- [ ] I've provided a detailed description
- [ ] The PR is scoped to a single task/feature
- [ ] I've included relevant tests (if tests are not included please provide the reason why they aren't)

### UI changes

> Check one of the following checkboxes

- [ ] My PR is not introducing a UI change
- [ ] My PR is introducing UI changes and I provided all screenshots in the PR description

#### PR type

> check one of the following type and make sure all related checkboxes are checked.

- [ ] My PR is a part of a new feature or a feature improvement
  - [ ] I've provided a link in the description to the relevant card in the Zapp cycle feature rollout Trello board.
- [ ] My PR is a bug fix
  - [ ] I provided a link in the description to the relevant Jira ticket or provided the following in the PR description:
    - steps to reproduce a bug
    - expected result

### Having problem feeling out the checklist / Conforming to guidelines - explain why and consult Zapp tech lead / Head of product

2022-07-25 08:25 UTC, f-roland commented
@alexzchut I ran local builds and builds from zapp by temporarily pointing the latest dev SDK to this branch, and all seems good. 
Can you give it a go locally (requires to update zapptool to 4.4.1) and review this ?

2022-07-25 16:22 UTC, alexzchut requested changes

2022-07-25 16:22 UTC, alexzchut commented on .circleci/config.yml
> +        cd $TARGET_FOLDER && yarn && bundle exec pod update && cd ..
yarn is being called in separate step, this is for cocoa pods updates only

2022-07-25 16:29 UTC, f-roland commented on .circleci/config.yml
> +        cd $TARGET_FOLDER && yarn && bundle exec pod update && cd ..
yeah I know, but for some reason, the postinstall patch was not applied when running pod install. I noticed this a few times locally as well. 
It doesn't really add much time as the install is cached anyway, but at least we're sure we don't get build errors because the RN files are not properly patched

2022-07-31 08:46 UTC, alexzchut commented on .circleci/config.yml
> +        cd $TARGET_FOLDER && yarn && bundle exec pod update && cd ..
I see that `yarn` is being called as a part of zapptool call, in `prepare_application_environment` which is in previous step. If this occurs only locally and we don't have this issue on circle builds (at least we didn't see this issue before) I don't think we need to add this additional call and mix

2022-07-31 09:57 UTC, alexzchut approved these changes

2022-07-31 10:01 UTC, merged